#!/usr/bin/with-contenv bash

set -o errexit

if command -v apt-get >/dev/null; then
  apt-get update
  apt-get install -y mkvtoolnix
  apt-get clean
fi

if command -v apk >/dev/null; then
  apk --update add mkvtoolnix --no-cache
fi
