#!/usr/bin/with-contenv bash

set -o errexit

if [ -f /usr/bin/apt-get ]; then
  apt-get update
  apt-get install -y mkvtoolnix
  apt-get clean
elif [ -f /usr/bin/apk ]; then
  apk --update add mkvtoolnix --no-cache
fi
