#!/usr/bin/with-contenv bash

set -o errexit

if [ -f /usr/bin/apt-get ]; then
  apt-get update
  apt-get install -y unzip
  apt-get clean
elif [ -f /usr/bin/apk ]; then
  apk --update add unzip --no-cache
fi

curl --output /tmp/nzb-notify.zip https://codeload.github.com/caronc/nzb-notify/zip/refs/heads/master

unzip /tmp/nzb-notify.zip -d /tmp

ls /tmp/nzb-notify-master | grep -v "requirements.txt" | xargs -rn1 -I{} mv /tmp/nzb-notify-master/{} /app/sabnzbd/scripts

pip install -r /tmp/nzb-notify-master/requirements.txt
